In [2]:
import tensorflow as tf

In [10]:
const=tf.constant(10)

In [11]:
string=tf.constant("Lokesh")

In [5]:
zeros=tf.zeros((4,4))

In [6]:
ones=tf.ones((4,4))

In [7]:
randn=tf.random_normal((4,4),mean=0.0,stddev=1.0)

In [9]:
randu=tf.random_uniform((4,4),minval=0.0,maxval=1.0)

In [12]:
mat=[const,string,zeros,ones,randn,randu]

In [13]:
sess = tf.InteractiveSession()

In [16]:
for op in mat:
    print(sess.run(op))
    print('\n')

10


b'Lokesh'


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 1.7479227   1.039212   -0.8272115  -0.27596122]
 [ 1.016581   -0.85719985 -0.5205489  -0.31362268]
 [ 1.0189314   0.7328869  -1.119774    0.6432117 ]
 [ 0.4713666  -0.4929382  -0.520072    0.2092591 ]]


[[0.6279514  0.8227067  0.68083954 0.15375972]
 [0.70921624 0.01674306 0.00506043 0.29088628]
 [0.76854587 0.7808422  0.42990005 0.29765892]
 [0.6018611  0.8383049  0.29407144 0.52379346]]




In [18]:
for op in mat:
    print(op.eval())

10
b'Lokesh'
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 1.2327474   0.4868338  -1.0029768  -0.30377382]
 [ 0.937805   -1.3072459  -0.48327848 -0.97522044]
 [ 1.2025226   0.42054254 -0.9652709  -0.6769528 ]
 [-1.8099891   1.1332657   0.6521404   0.5725198 ]]
[[0.5407139  0.16649568 0.03448391 0.22446883]
 [0.69254315 0.6105273  0.34278572 0.71644735]
 [0.76811576 0.37286544 0.24208641 0.19110215]
 [0.4628569  0.75366914 0.8838694  0.12946463]]
