In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
x=np.arange(10).reshape((5,2))
y=range(5)

print(x)
print(list(y))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0, 1, 2, 3, 4]


In [4]:
#random_state is the seed used by the random number generator.
#If RandomState instance, random_state is the random number generator; 
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=25)

In [5]:
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[6 7]
 [4 5]
 [8 9]]
[3, 2, 4]
[[0 1]
 [2 3]]
[0, 1]


In [6]:
train_test_split(y, shuffle=False)

[[0, 1, 2], [3, 4]]